/**
 * Sample Pet clinic play 2.6 apis
 * Sample Pet clinic play 2.6 apis
 *
 * OpenAPI spec version: 0.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The ActionAnyContent model module.
* @module model/ActionAnyContent
* @version 0.2
*/
export default class ActionAnyContent {
    /**
    * Constructs a new <code>ActionAnyContent</code>.
    * @alias module:model/ActionAnyContent
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>ActionAnyContent</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/ActionAnyContent} obj Optional instance to populate.
    * @return {module:model/ActionAnyContent} The populated <code>ActionAnyContent</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ActionAnyContent();

            
            
            

        }
        return obj;
    }









}


